### ISSUE TITLE
WIN10环境无法启动

### ISSUE THREAD

**Issue by Larliers** [krrcream/krr-s-osumania-anyKeys-converter#3]
双击/开发者模式Exe后没有任何反应，换Win11可以启动

**Comment by krrcream** [comment]
可能是使用的库不支持win10，我现在在做V1.0版本，现在降级到PY3.8打算让xp也能打开。到时候我把所用的库的版本都调整一下应该就能启动了？

**Comment by krrcream** [comment]
可能是使用的库不支持win10，我现在在做V1.0版本，现在降级到PY3.8打算让xp也能打开。到时候我把所用的库的版本都调整一下应该就能启动了？

**Comment by krrcream** [comment]
感谢提出问题。我正在换成python3.8，让XP也能启动。可能是一些库不支持WIN10? 后边做完我把库的版本都重新选择应该就能解决了。等下个版本吧。

**Comment by krrcream** [comment]
搞定，V1.0.1改成了python3.8.10来写，现在WIN7都能启动了
